[tool.poetry]
name = "pyroll-integral-thermal"
version = "2.0.0a"
description = "Plugin for PyRoll providing an integral approach for thermal modelling."
authors = [
    "Max Weiner <max.weiner@imf.tu-freiberg.de>",
    "Christoph Renzing <christoph.renzing@imf.tu-freiberg.de>",
]
license = "BSD-3-Clause"
homepage = "https://pyroll-project.github.io/"
repository = "https://github.com/pyroll-project/pyroll-integral-thermal"
documentation = "https://pyroll-project.github.io/modules/pyroll-integral-thermal/docs/docs"
packages = [
    { include = "pyroll/integral_thermal" }
]
readme = "README.md"
classifiers = [
    "Intended Audience :: Science/Research",
    "Intended Audience :: Manufacturing",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering"
]

[tool.poetry.dependencies]
python = ">=3.9, <4.0"
pyroll-core = "^2.0.0a"

[tool.poetry.dev-dependencies]
pytest = "^7.0.0"

[tool.poetry.group.report]
optional = true

[tool.poetry.group.report.dependencies]
pyroll-report = "^2.0.0a"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
